export default function HypothesesPage() {
  return (
    <div>
      <h1 className="text-3xl font-bold text-slate-900 mb-6">
        Drug Repurposing Hypotheses
      </h1>
      <p className="text-slate-500">
        Hypotheses will appear here once generated by the analysis engine.
      </p>
    </div>
  );
}
