from app.tasks.celery_app import celery_app
from app.tasks.ingest import (
    ingest_drugbank,
    ingest_pubchem,
    ingest_chembl,
    ingest_all_drugs,
    ingest_cbioportal,
    ingest_tcga,
    ingest_cosmic,
    ingest_all_cancer_data,
    ingest_kegg,
    ingest_reactome,
    ingest_string,
    ingest_uniprot,
    ingest_opentargets,
    ingest_all_pathways,
)
from app.tasks.reports import (
    generate_hypothesis_report_task,
    generate_cancer_summary_task,
    generate_novel_discoveries_task,
    generate_executive_summary_task,
    generate_all_reports,
)

__all__ = [
    "celery_app",
    "ingest_drugbank",
    "ingest_pubchem",
    "ingest_chembl",
    "ingest_all_drugs",
    "ingest_cbioportal",
    "ingest_tcga",
    "ingest_cosmic",
    "ingest_all_cancer_data",
    "ingest_kegg",
    "ingest_reactome",
    "ingest_string",
    "ingest_uniprot",
    "ingest_opentargets",
    "ingest_all_pathways",
    "generate_hypothesis_report_task",
    "generate_cancer_summary_task",
    "generate_novel_discoveries_task",
    "generate_executive_summary_task",
    "generate_all_reports",
]
