"""Add GNN link prediction, literature monitoring, and score history tables.

New tables:
  - gnn_training_runs: Stores GNN training run metadata and metrics
  - gnn_predictions: Cached GNN link predictions per drug-cancer pair
  - score_history: Tracks hypothesis score changes over time
  - literature_alerts: Alerts generated by literature monitoring
  - monitoring_config: Configuration for literature monitoring scheduler

Also adds gnn_link_score column to hypotheses table.

Revision ID: 010
Revises: 009
Create Date: 2026-02-20 10:00:00.000000
"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy import inspect
from sqlalchemy.dialects.postgresql import JSONB

revision = "010"
down_revision = "009"
branch_labels = None
depends_on = None


def _table_exists(conn, name: str) -> bool:
    return name in inspect(conn).get_table_names()


def _column_exists(conn, table: str, column: str) -> bool:
    if not _table_exists(conn, table):
        return False
    cols = [c["name"] for c in inspect(conn).get_columns(table)]
    return column in cols


def upgrade() -> None:
    conn = op.get_bind()

    # --- GNN Training Runs ---
    if not _table_exists(conn, "gnn_training_runs"):
        op.create_table(
            "gnn_training_runs",
            sa.Column("id", sa.Integer(), primary_key=True, autoincrement=True),
            sa.Column("status", sa.String(20), nullable=False, server_default="running"),
            sa.Column("epochs", sa.Integer(), nullable=False),
            sa.Column("hidden_channels", sa.Integer(), nullable=False, server_default="128"),
            sa.Column("out_channels", sa.Integer(), nullable=False, server_default="64"),
            sa.Column("n_drug_nodes", sa.Integer()),
            sa.Column("n_target_nodes", sa.Integer()),
            sa.Column("n_cancer_nodes", sa.Integer()),
            sa.Column("n_pathway_nodes", sa.Integer()),
            sa.Column("n_positive_labels", sa.Integer()),
            sa.Column("best_val_auc", sa.Float()),
            sa.Column("test_roc_auc", sa.Float()),
            sa.Column("test_avg_precision", sa.Float()),
            sa.Column("test_accuracy", sa.Float()),
            sa.Column("final_loss", sa.Float()),
            sa.Column("training_summary", JSONB, server_default="{}"),
            sa.Column("created_at", sa.DateTime(), server_default=sa.func.now(), nullable=False),
            sa.Column("completed_at", sa.DateTime()),
        )
        op.create_index("ix_gnn_runs_created", "gnn_training_runs", ["created_at"])

    # --- GNN Predictions ---
    if not _table_exists(conn, "gnn_predictions"):
        op.create_table(
            "gnn_predictions",
            sa.Column("id", sa.Integer(), primary_key=True, autoincrement=True),
            sa.Column("run_id", sa.Integer(), sa.ForeignKey("gnn_training_runs.id", ondelete="CASCADE"), nullable=False),
            sa.Column("drug_id", sa.Integer(), sa.ForeignKey("drugs.id", ondelete="CASCADE"), nullable=False),
            sa.Column("cancer_type_id", sa.Integer(), sa.ForeignKey("cancer_types.id", ondelete="CASCADE"), nullable=False),
            sa.Column("gnn_score", sa.Float(), nullable=False),
            sa.Column("created_at", sa.DateTime(), server_default=sa.func.now(), nullable=False),
        )
        op.create_index("ix_gnn_pred_drug_cancer", "gnn_predictions", ["drug_id", "cancer_type_id"])
        op.create_index("ix_gnn_pred_score", "gnn_predictions", [sa.text("gnn_score DESC")])
        op.create_index("ix_gnn_pred_run", "gnn_predictions", ["run_id"])

    # --- Score History ---
    if not _table_exists(conn, "score_history"):
        op.create_table(
            "score_history",
            sa.Column("id", sa.Integer(), primary_key=True, autoincrement=True),
            sa.Column("hypothesis_id", sa.Integer(), sa.ForeignKey("hypotheses.id", ondelete="CASCADE"), nullable=False),
            sa.Column("old_composite_score", sa.Float(), nullable=False),
            sa.Column("new_composite_score", sa.Float(), nullable=False),
            sa.Column("score_delta", sa.Float(), nullable=False),
            sa.Column("trigger", sa.String(50), nullable=False),
            sa.Column("trigger_details", JSONB, server_default="{}"),
            sa.Column("dimension_scores", JSONB),
            sa.Column("created_at", sa.DateTime(), server_default=sa.func.now(), nullable=False),
        )
        op.create_index("ix_score_history_hyp_date", "score_history", ["hypothesis_id", "created_at"])
        op.create_index("ix_score_history_delta", "score_history", [sa.text("score_delta DESC")])

    # --- Literature Alerts ---
    if not _table_exists(conn, "literature_alerts"):
        op.create_table(
            "literature_alerts",
            sa.Column("id", sa.Integer(), primary_key=True, autoincrement=True),
            sa.Column("hypothesis_id", sa.Integer(), sa.ForeignKey("hypotheses.id", ondelete="CASCADE"), nullable=False),
            sa.Column("alert_type", sa.String(50), nullable=False),
            sa.Column("severity", sa.String(20), nullable=False, server_default="info"),
            sa.Column("title", sa.String(500), nullable=False),
            sa.Column("description", sa.Text()),
            sa.Column("score_delta", sa.Float()),
            sa.Column("source_pmid", sa.String(20)),
            sa.Column("source_nct_id", sa.String(20)),
            sa.Column("source_data", JSONB, server_default="{}"),
            sa.Column("is_read", sa.Integer(), server_default="0"),
            sa.Column("created_at", sa.DateTime(), server_default=sa.func.now(), nullable=False),
        )
        op.create_index("ix_lit_alert_unread", "literature_alerts", ["is_read", "created_at"])
        op.create_index("ix_lit_alert_severity", "literature_alerts", ["severity", "created_at"])
        op.create_index("ix_lit_alert_hyp", "literature_alerts", ["hypothesis_id"])

    # --- Monitoring Config ---
    if not _table_exists(conn, "monitoring_config"):
        op.create_table(
            "monitoring_config",
            sa.Column("id", sa.Integer(), primary_key=True, autoincrement=True),
            sa.Column("hypothesis_id", sa.Integer(), sa.ForeignKey("hypotheses.id", ondelete="CASCADE"), nullable=False),
            sa.Column("is_active", sa.Integer(), nullable=False, server_default="1"),
            sa.Column("alert_threshold", sa.Float(), nullable=False, server_default="5.0"),
            sa.Column("last_checked_at", sa.DateTime()),
            sa.Column("check_interval_hours", sa.Integer(), nullable=False, server_default="168"),
            sa.Column("created_at", sa.DateTime(), server_default=sa.func.now(), nullable=False),
        )
        op.create_index("ix_monitoring_active", "monitoring_config", ["is_active", "last_checked_at"])

    # --- Add gnn_link_score to hypotheses ---
    if not _column_exists(conn, "hypotheses", "gnn_link_score"):
        op.add_column("hypotheses", sa.Column("gnn_link_score", sa.Float()))


def downgrade() -> None:
    conn = op.get_bind()

    if _column_exists(conn, "hypotheses", "gnn_link_score"):
        op.drop_column("hypotheses", "gnn_link_score")

    for table in ("monitoring_config", "literature_alerts", "score_history", "gnn_predictions", "gnn_training_runs"):
        if _table_exists(conn, table):
            op.drop_table(table)
